### ISSUE TITLE
Confusing typo in instructions

### ISSUE THREAD

**Issue by zshoorbajee** [learn-co-curriculum/dsc-word-vectorization-lab#3]
## Link to Canvas

https://learning.flatironschool.com/courses/4959/assignments/175785?module_item_id=386234

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [x] Instructions unclear
- [ ] Other (explain below)

### Source

```
Great. Now, write a function that takes in songs that have had their brackets removed, joins all of the lines into a single string, and then uses tokenize() on it to get a fully tokenized version of the song. Test this function on song_without_brackets to ensure that the function works.
```

### Concern

In the context of the problem, I think it should say "and then uses **word_tokenize()** on it to get a fully tokenized version of the song."

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [x] IllumiDesk

**Comment by hoffm386** [comment]
Thanks for flagging! Resolved by https://github.com/learn-co-curriculum/dsc-word-vectorization-lab/commit/ca8dfb73f0eb55c75732556ee9a45846fd2f1ceb
